### ISSUE TITLE
2D PDE solving: x-y index of u arrays might be mistaken

### ISSUE THREAD

**Issue by ssssOO** [barbagroup/CFDPython#11]
Dear BarbaGroud,

Thank you for sharing your work, it's awesome. But I'm having a hard time understanding your 2D implementation. In every of the notebooks I can see that the u is initialised as:

u = np.ones((ny,nx))

This means that the rows of the u array are related to the y direction and the columns are related to the x direction.

Furthermore when (for example) the 2D linear burger equation is solved you are using the following expression:

c*dt/dx*(un[i,j] - un[i-1,j]) 

To evaluate the derivative in the x-direction. As far as I'm concerned the rows of un, do have the information of the y axis, and thus you should be using dy instead of dx. This problem is not raised up because you are using the same dimensions and subdivisions for the x and y axis, but whenever this is changed there will be some errors.

The problem could be solved changing the u initialisation to:

u = np.ones((nx,ny))

Although the plots should be using the transposed of u in order to get the right axis.

Hope I'm wrong with my comments, but I've been thinking about this for a long time and I just cannot see if I'm making a mistake.

Thank you very much.

**Comment by gforsyth** [comment]
Hey @ssssOO , 

You're correct in your comments and we need to fix that.  We generally choose to initialize arrays as ((ny,nx)) because it's a better spatial match for how we usually think of the xy-plane (i.e. the x-axis is horizontal and the y-axis is vertical).  While I agree that your fix will solve the dy vs. dx issue, I think the better idea (although it's more work) is to fix the discretized PDEs.

I'm going to try to get to this today but I need to see how wide the problem is first.  Thanks for bringing it to our attention and definitely let me know if you have any other questions or concerns.

**Comment by ssssOO** [comment]
Dear gforsyth,

Thank you for the quick answer. As I saw that things didn't match I modified some of your code to deal with the mistake.

The easiest way of doing this is changing dx for dy and viceversa, whenever you calculate $u_i^{n+1}$. Let me ilustrate it with a linear convection 2D example:

Original: 

u[1:,1:]=un[1:,1:]-(c*dt/dx*(un[1:,1:]-un[1:,:-1]))-(c*dt/dy*(un[1:,1:]-un[:-1,1:]))

New:

u[1:,1:]=un[1:,1:]-(c*dt/dy*(un[1:,1:]-un[1:,:-1]))-(c*dt/dx*(un[1:,1:]-un[:-1,1:]))

This should work if the same scheme is used for the x and y derivative.

I could maybe help you uploading some commits for your code, although I'm not an expert.

**Comment by gforsyth** [comment]
Hi @ssssOO , 

Your example is definitely correct, but in the later lessons it isn't quite so simple, so a whole load of changes had to be made.  That said, I think I've fixed all of the index problems throughout the lessons.  Let me know if you spot any more mistakes!  Thanks!
