### ISSUE TITLE
Typo in the Poisson equation discretization in Step 11

### ISSUE THREAD

**Issue by peterparity** [barbagroup/CFDPython#58]
There is a strange (1 / Delta t) term in the discretized Poisson equation that is present in the written equation, the Python code (in the build_up_b function), and the corresponding Youtube video. This seems to make the solution unstable for small time steps. I think this may be due to a misapplication of discretization to a time derivative of div v. For an incompressible fluid, div v = 0 so this term should vanish. In any case, just tacking on a (1 / Delta t) is not the correct way to discretize a time derivative.

**Comment by piyueh** [comment]
In my personal opinion, the technique used in step 11 is a modified/simplified version of the so-called MAC method (Harlow & Welch, 1965). The divergence operator is applied to the temporally discretized momentum equations (i.e., semi-discretized), not to the original/continuous PDE. After this step, we get two temporal discretization term in the pressure: `(div U^n) / Delta t` and `(div U^(n+1)) / Delta t`. We want `(div U^(n+1)) / Delta t` to be zero, so we eliminate it from the equation. We are not sure if `(div U^n) / Delta t` is also zero (it may not be zero due to many reasons), so we keep it in the equation. And that's why you see that term in the equation. The original 1965 paper shows a more detailed derivation and how the `1/Delta t` term gets into it. 

The major differences in step 11 compared to the paper are:

1. The paper uses conservative format of the N-S equations, while CFDPython uses non-conservative forms.
2. The paper uses a staggered grid, while CFDPython uses a collocation grid.
3. CFDPython drops the Laplacian of the divergence term in the pressure equation, assuming this term can be ignored. 

I think the modifications in step 11 are to make the learning easier because this is just a beginners' class for CFD. Another place to find the derivation of the discretized pressure equation and MAC method is the book by McDonough, 2007 (see section 3.1.2). McDonough also briefly mentions that ignoring the Laplacian of divergence term may not cause big problems, but dropping the `1/Delta t` term causes instability issues.

**Ref**:
* Harlow, F. H., & Welch, J. E. (1965). Numerical calculation of time‐dependent viscous incompressible flow of fluid with free surface. *The physics of fluids*, 8(12), 2182-2189.
* McDonough, J. M. (2007). Lectures in computational fluid dynamics of incompressible flow: Mathematics, algorithms and implementations.

**Comment by peterparity** [comment]
That makes sense. Thanks for the references!
